name: Android CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract Version from build.gradle.kts
        id: extract_version
        run: |
          VERSION_NAME=$(grep -oP 'versionName = "\K[^"]+' app/build.gradle.kts)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Update README with Version
        run: |
          sed -i "s/APP_VERSION_PLACEHOLDER/${{ steps.extract_version.outputs.VERSION_NAME }}/g" README.md

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Build Bundle AAB
        run: ./gradlew bundleDebug

      - name: Build Release AAB
        run: ./gradlew bundleRelease
      
      - name: Configure Git and Push Updated README (Optional)
        if: always()
        continue-on-error: true
        run: |
          # Clean up any existing remote
          git remote rm origin || true
          # Set the remote URL with GITHUB_TOKEN
          git remote add origin https://github.com/${{ github.repository }}
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add README.md
          git commit -m "chore: Update README with app version ${{ steps.extract_version.outputs.VERSION_NAME }}" || true
          git push origin HEAD:master || true
